### ISSUE TITLE
Exception: Unknown custom metadata item kind: 7

### ISSUE THREAD

**Issue by amplicade** [rdio/vernacular#61]
Hi,

I'm receiving this exception lately. I was able to run Vernacular and already have some translations. After recent changes in my code it throws this error now. Any ideas?

`Unhandled Exception: Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 7
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModule Info info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleDefinition.ReadSymbols()
   at Vernacular.Parsers.AssemblyParser.Add(ModuleDefinition module)
   at Vernacular.Parsers.AssemblyParser.Add(String path)
   at Vernacular.Parsers.AggregateParser.Add(String path)
   at Vernacular.Tool.Entry.Main(String[] args)`

**Comment by amplicade** [comment]
Not using this library anymore.

**Comment by charlenni** [comment]
@TAC911 It would be nice, if you could say, what you use instead. Thank you.

**Comment by amplicade** [comment]
@charlenni in my case I'm using now the built-in feature for localization which is provided by Xamarin/Visual Studio for PCL projects.
